#!/bin/bash

SILENT=true
KILL_PARENT=true

if [[ "$1" == "-s" ]]; then
    KILL_PARENT=false
    shift
elif [[ "$1" == "-sd" ]]; then
    KILL_PARENT=false
    SILENT=false
    shift
fi

if [ "$SILENT" = true ]; then
    setsid -f "$@" > /dev/null 2>&1
else
    "$@" &
fi

if [ "$KILL_PARENT" = true ]; then
    sleep 0.2 
    kill -9 $PPID
fi
